### ISSUE TITLE
Output software version?

### ISSUE THREAD

**Issue by tomsing1** [awslabs/aws-simple-ec2-cli#45]
I installed `simple-ec2` on my Mac via homebrew, following the instructions on the README.md page. The version I got didn't support the `--tags` argument of the `simple-ec2 launch` command.  

When I re-installed the latest release from github
```
curl -Lo simple-ec2 https://github.com/awslabs/aws-simple-ec2-cli/releases/download/v0.7.0/simple-ec2-`uname | tr '[:upper:]' '[:lower:]'`-amd64
chmod +x simple-ec2
```
I got a later (?) version of the CLI that knew about the `--tags` argument.

Perhaps it would be useful to output the version of the installed CLI (e.g. via a `--version` / `-v` argument), so users can see quickly whether have the latest version installed?

**Comment by icarthick** [comment]
A simple version command could be added to the root command giving us the desired version output. @jillmon Am happy to work on this, let me know if you are looking for help
