### ISSUE TITLE
Offer an easy way to launch ARM64 instances in interactive mode

### ISSUE THREAD

**Issue by snay2** [awslabs/aws-simple-ec2-cli#52]
**Describe the feature**
As ARM64-based instances become more popular, developers may want to launch such instances with simple-ec2. The default instance type and all the suggested AMIs are AMD64-based. So while it is possible to to launch an ARM64 instance in interactive mode, there is not an easy default configuration, and it has some sharp edges (e.g., see [this issue](https://github.com/awslabs/aws-simple-ec2-cli/issues/51)).

It would be nice if the interactive CLI gave a suggestion for an ARM64 instance type as well as an AMD64 instance type, even if AMD64 remains the default.

It would also be nice if, after the user selects and ARM64 instance type, the AMI sugggestions include only AMIs that will actually run on that instance type.

**Is the feature request related to a problem?**
This is a developer pain point, even though it's not a bug per se.

**Describe alternatives you've considered**
If you already know the instance type and AMI ID you want, you can theoretically launch ARM64 instances with either interactive mode or command-line flags.

**Comment by icarthick** [comment]
@snay2 Happy to provide a PR with a fix for this. Let me know
