### ISSUE TITLE
Request Spot instance

### ISSUE THREAD

**Issue by brycahta** [awslabs/aws-simple-ec2-cli#55]
**Describe the feature**
I'd like to request a Spot instance using `simple-ec2` cli

**Is the feature request related to a problem?**
N/A

**Describe alternatives you've considered**
Using on-demand instance and not saving up to 90%

**Comment by icarthick** [comment]
@brycahta Am happy to work on this, would you mind if I opened a PR with some changes related to this feature?

**Comment by brycahta** [comment]
A design proposal doc is necessary because this feature is too complex to implement with a single PR. For next steps, the team will publish a design doc as a PR and welcome any input from the community before starting the implementation.

**Comment by iKarthik** [comment]
> A design proposal doc is necessary because this feature is too complex to implement with a single PR. For next steps, the team will publish a design doc as a PR and welcome any input from the community before starting the implementation.

While I appreciate the need for the proposal, it would been a better use of my time if you folks had told me that before I started the work on the PR. I explicitly solicited feedback on opening the PR before I began work on this for this very reason. Anyways thanks for allowing me to contribute.

**Comment by snay2** [comment]
We should update the README with the new output (slight table format modifications and the new Spot question) before we release.

**Comment by snay2** [comment]
This is available in [release `v0.9.0`](https://github.com/awslabs/aws-simple-ec2-cli/releases/tag/v0.9.0), through the artifacts or homebrew.
